services:

    #base Media form
    btn_media.form.default.media:
        class: Btn\MediaBundle\Form\MediaForm
        arguments: [ '@router' ]
        tags:
            - { name: form.type, alias: btn_media_form_media }

    btn_media.form.media: @btn_media.form.default.media

    btn_media.form.mediacategory:
        class: Btn\MediaBundle\Form\MediaCategoryForm
        arguments: [ '@router' ]
        tags:
            - { name: form.type, alias: btn_media_form_mediacategory }

    btn_media.form.type.media:
        class: Btn\MediaBundle\Form\Type\MediaType
        arguments:
            provider:   @btn_media.provider.media
            router:     @router
            translator: @translator
        tags:
            - { name: form.type, alias: btn_media }

    btn_media.form.type.file:
        class: Btn\MediaBundle\Form\Type\FileType
        tags:
            - { name: form.type, alias: btn_media_type_file }
