services:
    btn_media.provider.node_content_provider:
        class: Btn\NodesBundle\Provider\NodeContentProvider
        arguments:
            provider: @btn_media.provider.media_category
        tags:
            - { name: btn_nodes.content_provider }
