services:
    btn_media.provider.node_content_provider:
        class: Btn\NodeBundle\Provider\NodeContentProvider
        arguments:
            provider: @btn_media.provider.media_category
        tags:
            - { name: btn_node.content_provider }
