services:
    liip_imagine.data.loader.stream.btn_media:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - 'gaufrette://btn_media/'
        tags:
            - { name: 'liip_imagine.binary.loader', loader: 'stream.btn_media' }

    mediafile.manager:
        class: Btn\MediaBundle\Model\MediaFileManager
        arguments:
            em:          '@doctrine.orm.entity_manager'
            paginator:   '@knp_paginator'
            twig:        '@twig'
            formFactory: '@form.factory'
            container:   '@service_container'
            gaufrette:   '@knp_gaufrette.filesystem_map'

    extension.mediafile:
        class: Btn\MediaBundle\Twig\MediaFileExtension
        arguments: [ '@mediafile.manager' ]
        tags:
            - { name: twig.extension }

    btn_media.uploader:
        class: Btn\MediaBundle\Uploader\Uploader
        arguments: [ '@doctrine.orm.entity_manager', '%kernel.cache_dir%' ]
        calls:
            - [setAllowedExtensions, ['%btn_media.allowed_extensions%']]

    #upload adapter service
    btn_media.adapter:
        class: Btn\MediaBundle\Adapter\DefaultAdapter
        arguments:
            em:             '@doctrine.orm.entity_manager'
            formFactory:    '@form.factory'
            formName:       'btn_media_form_mediafile'
