services:
    liip_imagine.data.loader.stream.btn_media:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - 'gaufrette://btn_media/'
        tags:
            - { name: 'liip_imagine.binary.loader', loader: 'stream.btn_media' }

    mediafile.manager:
        class: Btn\MediaBundle\Model\MediaFileManager
        arguments:
            em:          '@doctrine.orm.entity_manager'
            paginator:   '@knp_paginator'
            twig:        '@twig'
            formFactory: '@form.factory'
            container:   '@service_container'
            gaufrette:   '@knp_gaufrette.filesystem_map'

    extension.mediafile:
        class: Btn\MediaBundle\Twig\MediaFileExtension
        arguments: [ '@mediafile.manager' ]
        tags:
            - { name: twig.extension }

    mediafile.uploader:
        class: Btn\MediaBundle\Model\MediaFileUploader
        arguments: [ '@doctrine.orm.entity_manager', '%kernel.cache_dir%' ]
        calls:
            - [setAllowedExtensions, ['%btn_media.allowed_extensions%']]

    #add link to the CP top menu
    btn_media.menu_navbar.media_item:
        class: %btn_admin.menu_item_class%
        factory_service: btn_admin.menu_builder
        factory_method: createMenu
        arguments: ["@request", "btn_media.route.index", "btn_media_mediacontrol_index", [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar }

    #base MediaFile form
    btn_media.form.mediafile:
        class: Btn\MediaBundle\Form\MediaFileForm
        arguments: [ '@router' ]
        tags:
            - { name: form.type, alias: btn_media_form_mediafile }

    btn_media.form.type.media:
        class: Btn\MediaBundle\Form\Type\MediaType
        tags:
            - { name: form.type, alias: btn_media_type_media }

    btn_media.form.type.file:
        class: Btn\MediaBundle\Form\Type\FileType
        tags:
            - { name: form.type, alias: btn_media_type_file }

    # btn_media.content_provider:
    #     class: Btn\NodesBundle\Service\RouteContentProvider
    #     arguments:
    #         availableRoutes: %btn.nodes.availableRoutes%
    #     tags:
    #         - { name: btn_nodes.content_provider }
