language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

before_script:
    - composer self-update
  
install:
    - composer install
    - npm install -g grunt-cli
    - npm install

script: grunt test

notifications:
    hipchat:
        rooms:
            secure: ZrlCOGUbyCXhRT4qWtES9QlcAEAKK384PrMk5FT0jwvk6I/cp4Nd8ygxA5F2+QG65ZJhGEkJZnLkSrCKJ/n37clEJ2QEjJLCdT/8TBjl73RF+maqGq7cwYetgx9ung/XGy6plZs8f1p1hub31dDIfFBMM0mbl5koEkAJkjWy7/4=
