parameters:
    btn_media.form.default.media.class: Btn\MediaBundle\Form\MediaForm
    btn_media.form.media_control.class: Btn\MediaBundle\Form\MediaControlForm
    btn_media.form.media_category_control.class: Btn\MediaBundle\Form\MediaCategoryControlForm
    btn_media.form.type.media.class: Btn\MediaBundle\Form\Type\MediaType
    btn_media.form.type.media_category.class: Btn\MediaBundle\Form\Type\MediaCategoryType
    btn_media.form.type.file.class: Btn\MediaBundle\Form\Type\FileType

services:
    #base Media form
    btn_media.form.media_control:
        class: %btn_media.form.media_control.class%
        parent: btn_admin.form.abstract
        calls:
            - [setClass, [%btn_media.media.class%]]
            - [setRouter, [@router]]
        tags:
            - { name: form.type, alias: btn_media_form_media_control }

    btn_media.form.media: @btn_media.form.media_control

    btn_media.form.media_category_control:
        class: %btn_media.form.media_category_control.class%
        parent: btn_admin.form.abstract
        calls:
            - [setClass, [%btn_media.media_category.class%]]
            - [setRouter, [@router]]
        tags:
            - { name: form.type, alias: btn_media_form_media_category_control }

    btn_media.form.type.media:
        class: %btn_media.form.type.media.class%
        calls:
            - [setEntityProvider, [@btn_media.provider.media]]
            - [setTranslator, [@translator]]
            - [setRouter, [@router]]
            - [setAssetLoader, [@btn_base.asset_loader]]
        tags:
            - { name: form.type, alias: btn_media }

    btn_media.form.type.media_category:
        class: %btn_media.form.type.media_category.class%
        calls:
            - [setEntityProvider, [@btn_media.provider.media_category]]
        tags:
            - { name: form.type, alias: btn_media_category }


    btn_media.form.type.file:
        class: %btn_media.form.type.file.class%
        tags:
            - { name: form.type, alias: btn_media_type_file }
