parameters:
    btn_media.form.default.media.class: Btn\MediaBundle\Form\MediaForm
    btn_media.form.media_control.class: Btn\MediaBundle\Form\MediaControlForm
    btn_media.form.media_category_control.class: Btn\MediaBundle\Form\MediaCategoryControlForm
    btn_media.form.type.media.class: Btn\MediaBundle\Form\Type\MediaType
    btn_media.form.type.media_category.class: Btn\MediaBundle\Form\Type\MediaCategoryType
    btn_media.form.type.media_group.class: Btn\MediaBundle\Form\Type\MediaGroupType
    btn_media.form.type.media_embedded.class: Btn\MediaBundle\Form\Type\MediaEmbeddedType
    btn_media.form.type.file.class: Btn\MediaBundle\Form\Type\FileType
    btn_media.form.filter.media.class: Btn\MediaBundle\Form\Filter\MediaFilterForm

services:
    #base Media form
    btn_media.form.media_control:
        class: %btn_media.form.media_control.class%
        parent: btn_admin.form.abstract
        calls:
            - [setAllowedExtensions, [%btn_media.media.allowed_extensions%]]
            - [setMaxSize, [%btn_media.media.max_size%]]
            - [setClass, [%btn_media.media.class%]]
            - [setRouter, [@router]]
        tags:
            - { name: form.type, alias: btn_media_form_media_control }

    btn_media.form.media: @btn_media.form.media_control

    btn_media.form.media_category_control:
        class: %btn_media.form.media_category_control.class%
        parent: btn_admin.form.abstract
        calls:
            - [setClass, [%btn_media.media_category.class%]]
            - [setRouter, [@router]]
        tags:
            - { name: form.type, alias: btn_media_form_media_category_control }

    btn_media.form.type.media:
        class: %btn_media.form.type.media.class%
        calls:
            - [setClass, [%btn_media.media.class%]]
            - [setEntityProvider, [@btn_media.provider.media]]
            - [setTranslator, [@translator]]
            - [setRouter, [@router]]
            - [setAssetLoader, [@btn_base.asset_loader]]
        tags:
            - { name: form.type, alias: btn_media }

    btn_media.form.type.media_category:
        class: %btn_media.form.type.media_category.class%
        calls:
            - [setEntityProvider, [@btn_media.provider.media_category]]
        tags:
            - { name: form.type, alias: btn_media_category }

    btn_media.form.type.media_group:
        class: %btn_media.form.type.media_group.class%
        arguments:
          - %btn_media.media.groups%
        tags:
            - { name: form.type, alias: btn_media_group }

    btn_media.form.type.media_embedded:
        class: %btn_media.form.type.media_embedded.class%
        tags:
            - { name: form.type, alias: btn_media_embedded }

    btn_media.form.type.file:
        class: %btn_media.form.type.file.class%
        tags:
            - { name: form.type, alias: btn_media_type_file }

    btn_media.form.filter.media:
        public: false
        class: %btn_media.form.filter.media.class%
