liip_imagine:
    driver: gd
    data_loader: stream.btn_media
    filter_sets:
        btn_media_icon:
            quality: 75
            data_loader: stream.btn_media_icon
            filters:
                strip: ~
                thumbnail: { size: [166, 166], mode: outbound }
        btn_media_thumb:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [166, 166], mode: outbound }
        btn_media_preview:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [500, 500], mode: inset }
