liip_imagine:
    driver: gd
    web_root: %web_root%
    cache_prefix:  uploads/media/cache
    cache_clearer: false
    filter_sets:
        btn_media_thumb:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [166, 166], mode: outbound }
        btn_media_preview:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [500, 500], mode: inset }
