services:
    #add link to the CP top menu
    btn_media.menu_navbar.media_item:
        public: false
        class: %btn_admin.menu_item.class%
        factory: [@btn_admin.menu_builder, createMenu]
        arguments: [@request, 'btn_media.menu_navbar.media_item.label', 'btn_media_mediacontrol_media_index', [], []]
        scope: request
        tags:
            - { name: btn_admin.menu_item , parent: btn_admin.menu_navbar }
